### ISSUE TITLE
수정 요청 건의사항

### ISSUE THREAD

**Issue by skm0619** [Team-CMD/StarterSeason_Winter_Team_A#1]
x축 좌우 이동이 + - 2씩 이동하는데 현재 b조의 바둑판 맵 함수를 적용하고 보니 +-1로 수정해야 할 것 같슴다

**Comment by JH9892** [comment]
그건 우리조 바둑판 크기에 따라 조정하는거라 맵구현이 되면 수정하면 될 것 같습니다.

**Comment by ash-hun** [comment]
> x축 좌우 이동이 + - 2씩 이동하는데 현재 b조의 바둑판 맵 함수를 적용하고 보니 +-1로 수정해야 할 것 같슴다

그건 우리조 바둑판 크기에 따라 조정하는거라 맵구현이 되면 수정하면 될 것 같습니다.

**Comment by skm0619** [comment]
아 잘못달았다. b조꺼 적용이아니라 우리꺼 적용해봤는데 1로 값 수정해야 맞게 움직여용

**Comment by ash-hun** [comment]
> 아 잘못달았다. b조꺼 적용이아니라 우리꺼 적용해봤는데 1로 값 수정해야 맞게 움직여용

A조 map이 안올라와있는데 어떻게 1로 수정해야 맞게 움직인다는걸 알죠?

**Comment by ash-hun** [comment]
요청사항 파악 후 수정완료하였습니다!
